### ISSUE TITLE
version comparison of string values

### ISSUE THREAD

**Issue by ashwilliams1** [maragudk/migrate#22] opened 2021-11-19 04:56 UTC
:wave: hey there I came across this package (which looks really cool) and I noticed this line:

```Go
if thisVersion > currentVersion {
	continue
}
```

I was wondering how the version compare would handle this scenario:

```
9.up.sql
10.up.sql
```

given the following result when comparing the two version strings:

```Go
fmt.Println("9" > "10")
// true
```

have you considered parsing the version as a number?

or maybe you would consider allowing the user to customize the regular expression to ensure extra safety?  For example I could customize the up and down expressions to ensure the version is expressed as a date:

```Go
// 20210510.up.sql
regexp.MustCompile(`^([\d]{7}).up.sql$`)
```

or I could customize the expression to ignore the trailing description and only use the digits for comparison:

```Go
// 20210510-create-user-table.up.sql
regexp.MustCompile(`^([\d]{7})[\w-]+.up.sql$`)
```

**Comment by markuswustenberg** [comment] 2021-11-19 08:22
Hey @ashwilliams1! Thank you for your feedback. 😊

Yes, versions are compared lexically, not numerically. This allows for descriptive versions such as `212-doing-something`, and not just numbers. The easiest workaround to having low-digit version numbers is to use zero prefixes. But I would suggest doing what the built-in command does and use timestamps instead. I would be hesitant to add a new sorting functionality, for the sake of simplicity of the API.

For the latter part: I just added `Before` and `After` callback functions just yesterday. In `Before`, which gets the version string, you could do whatever validation you need to do and potentially error. I think that would cover your use case?

**Comment by markuswustenberg** [comment] 2021-11-19 08:30
But I definitely get your point. Even the example in the README uses simple version numbers. Hmm. I'll think about what the best course of action is.

**Comment by ashwilliams1** [comment] 2021-11-19 13:40
would you maybe consider something like this?

```diff
type Options struct {
+	MatchUp   *regexp.Regexp
+	MatchDown *regexp.Regexp
	After     callback
	Before    callback
	DB        *sql.DB
	FS        fs.FS
	Table     string
}
```

```
func New(opts Options) *Migrator {
+	if opts.MatchUp == nil {
+		opts.MatchUp = upMatcher
+	}
+	if opts.MatchDown == nil {
+		opts.MatchDown = downMatcher
+	}
```

I think this would get me half way there.

**Comment by ashwilliams1** [comment] 2021-11-19 15:31
maybe add a compare function?  I could use this to parse and compare strings?

```
+type comparer Compare(a, b string) int

type Options struct {
+	Compare   comparer
	After     callback
	Before    callback
	DB        *sql.DB
	FS        fs.FS
	Table     string
}

func New(opts Options) *Migrator {
+	if opts.Compare == nil {
+		opts.Compare = strings.Compare
+	}
```

I guess it would be nice if I could somehow customize how versions are parsed and how they are compared.  I think this would allow you to keep this package relatively simple, while giving consumers of this package the flexibility they may need to tweak things.  win win :)

**Comment by markuswustenberg** [comment] 2021-11-20 07:04
I was also thinking a compare function. Something like the functions used to sort in the standard lib.

I'm not 100% certain yet, but I think you have me convinced this is a good idea to add. 😉 Stay tuned.

**Comment by markuswustenberg** [comment] 2021-11-22 09:21
> EDIT: just a heads up that `"0009" > "0010" == true` so this may not solve it.

@ashwilliams1 Just saw your edit. That expression is false. 😊 Zero prefixing should work as intended. https://play.golang.org/p/X997rVOHIbg

**Comment by markuswustenberg** [comment] 2022-03-30 08:28
Closing this now, may revisit if the need arises.

**Closed by markuswustenberg** 2022-03-30 08:28 UTC
